pipeline:
  identifier: Build_keen_software_templatesSamples_1704416826816
  name: Build templatesSamples
  orgIdentifier: default
  projectIdentifier: playground
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.github
        repoName: keen-software/templatesSamples
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Sh
                    command: env
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
